### ISSUE TITLE
Use the sample

### ISSUE THREAD

**Issue by yangxj96** [postgis/postgis-java#112]
Can you provide a sample project or a quick start?
I think he can meet my needs.
But I don't know how to use it
xD

**Comment by phillipross** [comment]
Have a look at the test classes in the postgis-jdbc module to see some example usages.  I hope that helps.
Also feel free to open a discussion in the discussions section of this repo.

**Comment by yangxj96** [comment]
> Have a look at the test classes in the postgis-jdbc module to see some example usages. I hope that helps. Also feel free to open a discussion in the discussions section of this repo.

ok,ty
