### ISSUE TITLE
Vulnerability in subDependency of postgressql:42.7.1

### ISSUE THREAD

**Issue by DmitryFleisher** [postgis/postgis-java#133]
The latest version of postgis bindings (2023.1.0) contains very vulnerable dependency.
Can it be updated to major version?
https://mvnrepository.com/artifact/net.postgis/postgis-jdbc/2023.1.0
Thank in advance!

**Comment by phillipross** [comment]
resolve in release [v2024.1.0](https://github.com/postgis/postgis-java/releases/tag/v2024.1.0)
