### ISSUE TITLE
Remove dependency on AWT classes

### ISSUE THREAD

**Issue by frode-carlsen** [postgis/postgis-java#2]
Currently the jdbc module has dependencies on java.awt in org.postgis.java2d

As of Java9 / Project jigsaw these will be part of a desktop module and may not be available server-side.  Would it be possible to break this dependency out? If anybody is using it, perhaps to a different project?

**Comment by phillipross** [comment]
:+1: 
Breaking the java2d code out is a good idea and has definite advantages.  It's definitely possible to do.  My propose that it's factored out to a separate module within the postgis-java project.  This will be possible to do in the very near future.  Cleanup of the build process is happening now.

**Comment by phillipross** [comment]
Integrated with merge of pull request #20 on change a7fe83521bc595a36adee6f8f6b607732510725b
