### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by pietermartin** [postgis/postgis-java#29]
Hi,

Any chance this can be deployed to maven central repository?
Thanks

**Comment by phillipross** [comment]
Yes, but I believe that we have to change the maven coordinates to point to postgis.net instead of postgis.org.  We were waiting for more feedback from folks who might see this change as problematic, but nobody has chimed in so I think we can move forward with it.

**Comment by pietermartin** [comment]
Great, I look forward to it.

**Comment by robe2** [comment]
Yes lets move forward.

**Comment by phillipross** [comment]
@pietermartin A snapshot release of 2.1.7.2 has been published to sonatype snapshot repos.  You can pull from there immediately if you'd like to test.  An actual 2.1.7.2 release will be published to sonatype snapshot repos shortly and then mirrored to the central repos.

**Comment by phillipross** [comment]
#30 v2.1-maintenance branch tagged with v2.1.7.2 and released to sonatype for mirroring to maven central.

**Comment by pietermartin** [comment]
+1

**Comment by phillipross** [comment]
v2.1.7.2 release artifacts are now mirrored to with [net.postgis](http://search.maven.org/#search%7Cga%7C1%7Cnet.postgis) groupId.
Closing out this issue.
