### ISSUE TITLE
Incorrect license headers

### ISSUE THREAD

**Issue by sebastic** [postgis/postgis-java#35]
The Debian FTP master reviewing the recent [postgis-java Debian package](https://tracker.debian.org/pkg/postgis-java) upload [commented](https://lists.alioth.debian.org/pipermail/pkg-grass-devel/2015-November/039567.html) that the license headers need to use the correct LGPL2.1+ template.

Most suggest that it's LGPL-2.1-only having leaving out the ', or (at your option) any later version`. For example:
```c
/*
 * DriverWrapperAutoprobe.java
 * 
 * PostGIS extension for PostgreSQL JDBC driver - Wrapper utility class
 * 
 * (C) 2005 Markus Schaber, markus.schaber@logix-tt.com
 * 
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA or visit the web at
 * http://www.gnu.org.
 * 
 */
```
The correct LGPL-2.1+ template is:
```c
/*
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
```
If the postgis-java source is not licensed under the LGPL-2.1+ (or later versions) this needs to be documented. The license referenced from the `pom.xml` ([lgpl-2.1.txt](http://www.gnu.org/licenses/lgpl-2.1.txt)) is LGPL-2.1+ not LGPL-2.1 (only).

**Comment by phillipross** [comment]
@sebastic Thanks for reporting this.  We'll get this fixed.

**Comment by phillipross** [comment]
Fixed on master w/ PR #36
Still should be updated on v2.1 maintenance branch.

**Comment by phillipross** [comment]
Fixed on v2.1-maintenance branch w/ PR #37

**Comment by phillipross** [comment]
@sebastic When you get a free moment, could you review the updated source header?  If it looks good, I'll close out this issue.  Thanks again!

**Comment by sebastic** [comment]
Thanks for the changes, it looks much better now.

There are still number of files left to fix under the `ejb2` & `ejb3` directories.

From the `licensecheck` run on the v2.1-maintenance branch @ 4c1c147:
```
ejb2/src/com/geodetix/geo/client/Client.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb2/src/com/geodetix/geo/exception/ApplicationGeoLayerException.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb2/src/com/geodetix/geo/dao/PostGisGeometryDAO.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb2/src/com/geodetix/geo/dao/PostGisGeometryDAOImpl.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb2/src/com/geodetix/geo/ejb/GeometryBean.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb2/src/com/geodetix/geo/ejb/GeometryFacadeBean.java: LGPL (with incorrect FSF address)
  [Copyright: 2006, Geodetix S.r.l. (http://www.geodetix.it)]

ejb3/src/org/postgis/hibernate/PostGISDialect.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/hibernate/ContainsExpression.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/hibernate/WithinExpression.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/hibernate/IntersectsExpression.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/hibernate/GeometryType.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/ejb/UserBean.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/ejb/UserBeanRemote.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/ejb/PersonEntity.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]

ejb3/src/org/postgis/ejb/mdb/IngestMDB.java: LGPL (with incorrect FSF address)
  [Copyright: 2006 Norman Barker <norman.barker@gmail.com>]
```
master @ 61cc13c has the same issues.

**Comment by phillipross** [comment]
@sebastic Thanks for checking this.

The contents of the ejb directories are essentially unmaintained.  It still exists in the repository as we've not decided what we should do with it yet.  The `pom.xml` file in the root directory never references these directories and the code is not built.  Is there a proper way to setup exclusions for the licensecheck infrastructure inside the repo so that it skips over certain paths?

**Comment by sebastic** [comment]
`licensecheck` is just a tool to review the license for source trees. My general use is to run `licensecheck --copyright -r *` from the root to have it process all files, but it also supports ignoring paths as documented in its manpage: [licensecheck(1)](http://manpages.debian.org/cgi-bin/man.cgi?query=licensecheck).

The FTP master review also checks the entire source tree, because the source cannot contain non-free licensed files if it is included in the main Debian repository. We therefore need to document the license & copyright for the entire upstream release + Debian packaging.

`ejb2/README` documents the license as LGPL-2.1+:
```
This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.
```
Fixing the headers to reflect this too shouldn't be an issue.

The `ejb3` tree lacks additional clear license statements, Norman Barker should be able to clarify the licensing in unambiguous terms.

To not have to deal with the unmaintained `ejb2` & `ejb3` trees, why not delete them from the source tree and leave it to an interested party to restore them from the repository history when there is an interest into maintaining them again?

**Comment by robe2** [comment]
I'd agree should just delete especially since you are not using.

**Comment by phillipross** [comment]
Thanks, I'm inclined to agree that deletion is the way to go.  As a courtesy, I'll try to ping Norman Baker at the gmail address to let him know we're going to remove the code but that it'll still be available in SCM history.  I'll replace the code with documentation and references explaining the deletion and where it can be found.
