### ISSUE TITLE
Minimal .jar Test Harness

### ISSUE THREAD

**Issue by darkblue-b** [postgis/postgis-java#38]
Write a small program to take a specified .jar plus a specified Postgres database, and make a collection of function calls to it.  Please note this idea appeared while testing the **OSGeo-Live**, using **OpenJDK 7**, **PostgreSQL 9.4** and **PostGIS 2.2** under **LUbuntu 1404**. An initial version should work in that environment.

**Comment by phillipross** [comment]
now available in v2.2.1
