### ISSUE TITLE
Change Logback dependencies to "provided" scope

### ISSUE THREAD

**Issue by aggregat4** [postgis/postgis-java#43]
The current postgis-jdbc artifact has hard "compile" scope dependencies on logback. This wreaks havoc with all consumers that don't use logback since it will be added into the dependency tree transitively and collide with other slf4j logging providers (like log4j). Clients have to explicitly exclude the logback dependencies to prevent this.

The concrete logging provider should probably be in "provided" scope so it does not get transitively inherited by consumers.

BTW the logback dependency comes in via the parent "postgis-java-aggregator" project.

**Comment by phillipross** [comment]
This issue is actually already resolved on master branch (PR #41)
We'll cut a new release with the change.
