### ISSUE TITLE
Issue with several postgis schemas in the same DB

### ISSUE THREAD

**Issue by geoffroya** [postgis/postgis-java#50]
Hi

We encountered an issue with a DB having several Postgis schemas. When the app starts and we issue a find on a table having a Geometry, the ```type``` is not ```geometry``` but ```\"public\".\"geometry\"```.

Strangely, if we issue a save to the table, and next a find, the ```type``` is correct.

To workaround this, we modified the JDBC driver to add the mapping between ```\"public\".\"geometry\"``` and ```PGgeometry```.

The PR is coming...

Best regards.

Geoff.

**Comment by geoffroya** [comment]
PR: https://github.com/postgis/postgis-java/pull/51

**Comment by phillipross** [comment]
resolved with pull request #57
