### ISSUE TITLE
Postgis 2.5 + postgres 11 and postgis jdbc

### ISSUE THREAD

**Issue by Trikke76** [postgis/postgis-java#72]
Hi
question will this postgis jdbc 2.3 work with postgres 11 and postgis 2.5 ? 
not sure how i need to look at the version number of this postgis jdbc is it related tot the postgis version or not at all ?

**Comment by nitehawk42** [comment]
As long as postgis-java is newer than the extension it should be ok. I am using postgis-jdbc 2.3.1, postgres 10, and postgis extension version 2.2.

To support Java 11, I did need to update JTS to 1.16.0. See this pull request:
https://github.com/postgis/postgis-java/pull/71

**Comment by phillipross** [comment]
The PostGIS java driver works with any "supported" version of PostGIS, and the version of the java driver does NOT correspond to versions of PostGIS, but merely happens to have the same version numbers for some releases.  We acknowledge that it's confusing for the time being, and plan to change the versioning scheme of the java driver to address this ;)

**Comment by Trikke76** [comment]
Ok thx for the confirmation on this
